### ISSUE TITLE
[Proposal] - Scope support

### ISSUE THREAD

**Issue by ebisbe** [rinvex/repository#100]
Hello,

I read the article at [The art of using repositories](https://blog.omranic.com/the-art-of-using-repositories-in-laravel-5-3-ee20a1eacb35) and thought that trying this repository would fit my actual project. After the first read I found that it was not caching at all the queries I wanted. I tryed hard but it not worked at all.
After leaving the package apart and trying again I've found that local scopes are not working correctly. Apart from that repository I'm using [jenssegers/Laravel-MongoDB](https://github.com/jenssegers/Laravel-MongoDB) and when I'm using the local scope it crashes with the findAll() method from the repository. Global scopes are working fine because they use the Builder class. 

`
class PublishedProduct extends Product
{
    use PublishedProductsTrait;

```
/**
 * @param $query
 * @param bool $featured
 * @return \Illuminate\Database\Eloquent\Builder
 */
public function scopeFeatured($query, $featured = true)
{
    return $query->where('featured', (bool)$featured);
}
```

}`

PublishedProduct extends Product class and adds with a trait the published status to all queries. Product Extends Jenssegers\Mongodb\Eloquent for mongoDB support. 

I can query with 
`$productsLeft = $product->where('featured', true)->limit(2)->findAll();`
But I think that 
`$productsRight = $product->featured()->limit(8)->findAll();`
Should work too.

Any idea?

**Comment by ionut-tanasa** [comment]
I'm having trouble understanding what are you trying to say here, mate.

Can you elaborate more?

**Comment by ebisbe** [comment]
In laravel there are Local scopes. [Local Scopes](https://laravel.com/docs/5.2/eloquent#local-scopes) and I had them on my model set up like the function below:
```
public function scopeFeatured($query, $featured = true)
{
    return $query->where('featured', (bool)$featured);
}
```
But when using the repository they don't work. 

I can query with
```$productsLeft = $productRepository->where('featured', true)->limit(2)->findAll();```
But I think that
```$productsRight = $productRepository->**featured**()->limit(8)->findAll();```
Should work too.

I don't know what more to say? Can you tell me which part you don't understand??

**Comment by ebisbe** [comment]
@ionut-tanasa

**Comment by Omranic** [comment]
Hello @ebisbe thank you for the report. It's true this package doesn't support scopes, yet as @ionut-tanasa pointed. But here's the deal, I'll be investigating this and will make sure to include it in the. Ext major release. Just after we release the currently under development rinvex/fort it's important to add support for scopes.

**Comment by ebisbe** [comment]
@Omranic No problem. I just spent try to figure out why the repository didn't worked. At the end I figured out that the scopes where the problem. I think that that should be pointed in some place to avoid missunderstundings. 

Great package by the way!

**Comment by Omranic** [comment]
Yeah, I really appreciate your report as this was forgotten 😄 
I hope you find  the article & package useful 👍
Will keep this issue open until further update.

**Comment by ebisbe** [comment]
By the way, global scopes work fine.

**Comment by Omranic** [comment]
Implemented in e690ae4021d06f10711d4651e0150f3bba49d6ec 👍

**Comment by ebisbe** [comment]
Nice! This when this will be available? Because I read that you merge to master once every 6 months, that's right?

**Comment by ebisbe** [comment]
@Omranic

**Comment by Omranic** [comment]
@ebisbe This week god willing, we switched to a faster release cycle, whenever it's ready, merge!  😉
