### ISSUE TITLE
Is it possible to disable cache temporarily?

### ISSUE THREAD

**Issue by ahmadazimi** [rinvex/repository#108]
Hi there,

Is there any way to disable cache temporarily for a specific query?

for example:

```php
$role = $this->repo->disableCache()->findAll();
```

**Comment by Omranic** [comment]
Hi @ahmadazimi 
Yup, you can do so as follows:
```php
// Disable cache for this individual query
$repository->setCacheLifetime(0);
```

Feel free to comment or re-open this issue if you need any further assistance 😉
