### ISSUE TITLE
OrderBy Not Working

### ISSUE THREAD

**Issue by Shipu** [rinvex/repository#110]
## Working
```
$this->postRepo->findAll()
```

## Not Working
```
$this->postRepo->orderBy('id', 'desc')->findAll()
```

**Comment by nahid** [comment]
Make sure you have column name `id`

**Comment by Omranic** [comment]
@Shipu Tested abd seems to be working fine.
Would you please tell me what's the result of your `orderBy` query?

**Comment by Omranic** [comment]
Couldn't reproduced!

**Comment by Shipu** [comment]
return unordered data.

**Comment by tucq88** [comment]
Do you know how to report a bug @Shipu  ?
