### ISSUE TITLE
Is Dirty

### ISSUE THREAD

**Issue by ebisbe** [rinvex/repository#112]
Hello, 
I've been busy trying to see if the isDirty() implementation for the repository is done but I think that it isn't. Is that right? I just don't want to flush cache when no real changes have been made.

**Comment by ionut-tanasa** [comment]
You are quite right there mate. Would you be kind enough to fix the merge conflicts in order to fix your PR so we can merge it? #113

**Comment by ebisbe** [comment]
@ionut-tanasa I will fix it but I'm not sure what to fix. I only see an error on a branch..

**Comment by Omranic** [comment]
Merged in #118 👍
