### ISSUE TITLE
How to make combination or and and in conditions

### ISSUE THREAD

**Issue by tsyrya** [rinvex/repository#116]
Hi,

How can I make a condition like:

column1 = value1 and column2 = value3 and (column3 = value3 or column4 = value4)

Thank you

**Comment by hansen1416** [comment]
You can try something like this:

```
$repository->where(column1, '=', value1, 'and')
            ->where(column2, '=', value3, 'and')
            ->where(function($q){
                $q->where(column3, '=', value3, 'or');
                $q->where(column4, '=', value4, 'or');
            })
```

Of course you can leave out '=' && 'and' since they are default value

**Comment by tsyrya** [comment]
Thank you for reply @hansen1416 
I have  tried this syntax:
```
->where(function($q){
    $q->where(column3, '=', value3, 'or');
    $q->where(column4, '=', value4, 'or');
})
```
But it seems it doesn't work for rinvex

**Comment by noxify** [comment]
Hi,

based on what I can see, the `where` method doesn't support where conditions with callbacks (correct me if I'm wrong).

In the laravel documentation there is a `orWhere` method, it seems that this will do what you want:

https://laravel.com/docs/5.3/queries#parameter-grouping

Maybe we/you/whoever can create a PR with the missing functionality or extending the existing `where` method to enable the possibility to send a function as first parameter.

Hope that helps.

**Comment by hansen1416** [comment]
Hi, @tsyrya @noxify 
At the first I thought the same that where doesn't support the closure syntax. But i've tried the following code.

```
class SpaceEloquentRepository extends EloquentRepository implements SpaceRepositoryContract
{
public function searchUserSpaceByName(string $name, int $user_id)
    {
        return $this
            ->where(function ($q) use ($user_id) {
                $q->where(function ($q) use ($user_id) {
                    $q->where('user_id', '<>', $user_id);
                    $q->where('share', '=', 1);
                })
                  ->where('user_id', '=', $user_id, 'or');
            })
            ->where('name', 'like', '%' . $name . '%')
            ->orderBy('sort', 'ASC')
            ->setCacheLifetime(0)
            ->findAll()
            ->toArray();
    }


}


class SpaceService implements SpaceServiceContract
{
public function searchSpace(string $name)
    {
        DB::enableQueryLog();
        $user_id = 1;
        $this->spaceRepo->searchUserSpaceByName($name, $user_id);
        return DB::getQueryLog();
    }
}


```

And this is what I get with laravel 5.3:

[
    {
        "query": "select * from `mp_space` where ((`user_id` <> ? and `share` = ?) or `user_id` = ?) and `name` like ? order by `sort` asc",
        "bindings": [
            1,
            1,
            1,
            "%dasdds%"
        ],
        "time": 0.68
    }
]

So I think it should work. Hope this could help.

**Comment by Omranic** [comment]
@tsyrya @hansen1416 @noxify Well, I've tested this situation, and used exactly the above code sample & it works perfectly as expected on the `develop` branch. The above scenario is completely valid and fully supported currently. Please feel free to recheck and open this issue again if you believe something missing. `develop` branch will be merged into `master` very soon.
