### ISSUE TITLE
Soft Deletes

### ISSUE THREAD

**Issue by brunogaspar** [rinvex/repository#122]
Hi again,

What's the best way to retrieve soft deleted models?

Currently i'm doing the following to retrieve all entities including the ones that are soft deleted:

```php
$entities = $this->repository->newQuery()->withTrashed()->get();
```

But would be nice to have a shorter way, i guess.

And how about on restoring a deleted item?

I guess that a new `restore($id)` method could be added?

Thanks!

**Comment by Omranic** [comment]
Yes, I agree. I'd be happy to accept PR for that and include in next release, otherwise we can schedule it for **v3.1.0** or something 😃

**Comment by brunogaspar** [comment]
Submitted a PR and it seems that `$entities = $this->repository->withTrashed()->get();` is already possible, so only the restore method was added.

**Comment by Omranic** [comment]
I like that, merged! Thanks @brunogaspar 👍
