### ISSUE TITLE
Method fill does not exist error on update

### ISSUE THREAD

**Issue by taliptako** [rinvex/repository#124]
I'm trying to update my post its have Eloquent Model by the way.I'm getting this error 
BadMethodCallException in Macroable.php line 74:
Method fill does not exist.
at Collection->__call('fill', array(array())) in EloquentRepository.php line 256

**Comment by Omranic** [comment]
Is your model extends any other packages or use some other traits, maybe?

**Comment by taliptako** [comment]
Yes it does 

`<?php

namespace App\Models;

use Carbon\Carbon;
use Date;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;

class Post extends Model implements HasMediaConversions
{
    use HasMediaTrait;`

implement : https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/Interfaces/HasMediaConversions.php
trait : https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/HasMediaTrait.php

**Comment by Omranic** [comment]
OK, let me check an example with `spatie/laravel-medialibrary` package, and get back to you again 👍

**Comment by taliptako** [comment]
It was because i forgot the give an id to function.

**Comment by prashant-pokhriyal** [comment]
@taliptako can you please tell me how did you solve this issue. I'm getting same error. Earlier it was working fine
