### ISSUE TITLE
Laravel 5.4 ?

### ISSUE THREAD

**Issue by sdebacker** [rinvex/repository#126]
Hello, is there a way to make it work with Laravel 5.4 ?

Thanks

**Comment by noxify** [comment]
If i'm not wrong - the develop branch should support laravel 5.4

**Comment by Omranic** [comment]
`develop` branch already supports **Laravel 5.4** (Duplicate #120, Reference 3a3ec7d7256b45168187c1168d5496e12ffb86f1) To be tagged soon.. 👍

**Comment by sdebacker** [comment]
Yes sorry. Thank you.
