### ISSUE TITLE
Fatal error with event listener on create and update

### ISSUE THREAD

**Issue by sdebacker** [rinvex/repository#127]
Hello,

With Laravel 5.4 and develop branch, every time I try to update a resource, I get this error:

```php
FatalThrowableError in RepositoryEventListener.php line 76:
Type error: Argument 1 passed to  Rinvex\Repository\Listeners\RepositoryEventListener::entityUpdating() must implement interface Rinvex\Repository\Contracts\RepositoryContract, string given`
```
Do you see what I'm doing wrong ?

**Comment by sdebacker** [comment]
For now I fixed the issue like that: https://github.com/TypiCMS/repository/commit/adf424bce8d83a3878ffaeb16cdd1885cf6ad626

**Comment by Omranic** [comment]
Sorry for the delay, please followup on the duplicate issue #131
