### ISSUE TITLE
some suggest about function generateCacheHash() in trait Cacheable 

### ISSUE THREAD

**Issue by deathkel** [rinvex/repository#128]
I think it's better to  use sth like request::fullUri instead of [model,where,relations,...] to generate hash. since
we may use some dynamic condition in our query(like where('created_at, '>', time()))

**Comment by Omranic** [comment]
I don't think that's a better idea, since most of the use cases depends on internal usage of repositories, without depending on URLs at all, so we still have many other variables to take into account (model, where, ..etc). And anyway what's expected of the query string is to be translated into where conditions at the end of the day, so it will be considered into hashing anyway :)

**Comment by deathkel** [comment]
here is my solution of dynamic query condition, use $model->toSql() to hashing,this function will return a string like this
```
select * from `flash_sales` where `delete` = ? and `endTime` > ? order by `startTime` asc
```
and I add a $modelnstance in EloquentRepository, in order to use all function of class Model.
```php
    protected $modelInstance;

    public function getModelInstance()
    {
        if (!$this->modelInstance) {
            $this->modelInstance = $this->createModel();
        }
        return $this->modelInstance;
    }

    public function find($id, $attributes = ['*'])
    {
        return $this->executeCallback(get_called_class(), __FUNCTION__, func_get_args(),
            function () use ($id, $attributes) {
                return $this->prepareQuery(
//------------------------------------
                     $this->getModelInstance()
//----------------------------------------
                )->find($id, $attributes);
            });
    }

```
In BaseRepository
```php
 protected function resetRepository()
    {
        $this->relations  = [];
        $this->where      = [];
        $this->whereIn    = [];
        $this->whereNotIn = [];
        $this->offset     = null;
        $this->limit      = null;
        $this->orderBy    = [];
        //--------------------------
        $this->modelInstance = null;
        //--------------------------

        return $this;
    }
```

**Comment by Omranic** [comment]
Good point, we actually used this approach in our newest package here https://github.com/rinvex/cacheable but first, would you please point out current shortage in this package -if any- to be clear why we're changing the hashing method? :)

**Comment by deathkel** [comment]
just when I use where('startTime', >, time()). I got a different hash everytime I make a request,since time().so I cant get my cache back  even I allready cached.

**Comment by Omranic** [comment]
Well, that issue will still be there with any hashing algorithm whatsoever, you're already generating a new query every time using `time()`, so how your approach will fix this?

**Comment by deathkel** [comment]
maybe use  toSql to hashing when I use time condition. since just use Model->toSql will  generate other problem

**Comment by Omranic** [comment]
Yes, using only `$model->toSql()` will introduce another issue, which is obviously returning one cache for multiple queries, so you still have to identify your query unique criteria :)
