### ISSUE TITLE
Fatal error with event listener on create and update

### ISSUE THREAD

**Issue by nahid** [rinvex/repository#131]
When I create new entity its show this error

Type error: Argument 1 passed to Rinvex\Repository\Listeners\RepositoryEventListener::entityCreating() must implement interface Rinvex\Repository\Contracts\RepositoryContract, string given

Note: I used laravel 5.4 version

**Comment by Omranic** [comment]
More description please? Error message or debug trace log maybe..

**Comment by noxify** [comment]
Same as #127 ?

**Comment by Omranic** [comment]
I'll check this..

**Comment by nahid** [comment]
When I create a new record in table its show this error

<img width="1059" alt="screen shot 2017-01-26 at 6 02 09 pm" src="https://cloud.githubusercontent.com/assets/3167309/22330708/c89cf492-e3f1-11e6-9397-81ed04b518a6.png">

my code is 

```php
$data = [
    'name'=>'some name',
    'email'=>'someone@example.com'
];

$user = $this->user->create($data);
```

**Comment by sdebacker** [comment]
Yes, same as #127.

**Comment by noxify** [comment]
@nahid - Are you using also Laravel 5.4 or 5.3?

**Comment by nahid** [comment]
Laravel 5.4

**Comment by Robert-Hansen** [comment]
i get the same error, is there anyways to fix it?

**Comment by Omranic** [comment]
Working on this right now, stay tuned..

**Comment by Omranic** [comment]
Well, I've tested both v2.x stable release, and `dev-develop` branch and they are working fine. You must never see the above error unless you're overriding the repository's `create` method and passing the wrong parameters to the fired `*.entity.creating` event. Reference:
https://github.com/rinvex/repository/blob/759cfcdb385fb53364b63b395f4fbe29d2e7dd23/src/Repositories/EloquentRepository.php#L203-L209

As you can see the fired event passes an instance of the current repository object, and not passing the class name or any strings:
```php
$this->getContainer('events')->fire($this->getRepositoryId().'.entity.creating', [$this, $entity]);
```

Please check your repository implementation and update this issue if you've further information.

@nahid @sdebacker @Robert-Hansen

**Comment by Robert-Hansen** [comment]
I still don't get it i use it just at the docs says to use it

`        $newUser = $this->userRepo->create([
            'username'  => $request->get('username'),
            'email'     => $request->get('email'),
            'password'  => bcrypt($request->get('password')),
            'ip'  => $request->getClientIp()
        ]);

        return response()->json([
           'user' => $newUser
        ]);`

what am i doing wrong?

**Comment by Omranic** [comment]
@Robert-Hansen Would you please post your `userRepo` class definition here..

**Comment by Robert-Hansen** [comment]
the userRepo is the UserRepository

```
class UserRepository extends EloquentRepository implements UserRepositoryContract
{

    public function __construct(Container $container)
    {
        $this->setContainer($container)
            ->setModel(User::class)
            ->setRepositoryId('rinvex.repository.uniqueid');
    }
}
```

**Comment by Omranic** [comment]
Sorry, my fault! Issue confirmed on Laravel v5.4+
Fix in progress..

**Comment by nahid** [comment]
How can I solve it?

**Comment by Omranic** [comment]
Fixed on **dev-develop** please composer update & post again if there's still any other issues. Sorry for the long wait 🙂  e2226399eb315f84f5ef3398c1ccdfec8540b56c

**Comment by Shipu** [comment]
Why it's required PHP 7 ?

**Comment by nahid** [comment]
@Shipu Laravel Framework required PHP version 5.6.4 not 5.4.6

**Comment by erenmustafaozdal** [comment]
@Omranic  Laravel 5.4 gives support for PHP 5.6.4. `dev-develop` Laravel 5.4 gives support, why does not php 5.6.4 give support?

**Comment by Shipu** [comment]
in my composer i use `"rinvex/repository": "^2.0"` 
and replace Listeners\RepositoryEventListener to https://github.com/rinvex/repository/blob/develop/src/Listeners/RepositoryEventListener.php
