### ISSUE TITLE
Why the condition where not readable in the query repository?

### ISSUE THREAD

**Issue by moschel26** [rinvex/repository#133]
My repository is like this :

    <?php
    
    namespace App\Repositories;
    
    use App\Models\Favorite;
    use Illuminate\Contracts\Container\Container;
    use Rinvex\Repository\Repositories\EloquentRepository;
    use DB;
    Use Log;
    
    class FavoriteRepository extends EloquentRepository
    {
        // Instantiate repository object with required data
        public function __construct(Container $container)
        {
            $this->setContainer($container)
                 ->setModel(Favorite::class)
                 ->setRepositoryId('rinvex.repository.uniqueid');
        }
    
        public function getFavoriteStore($user_id, $id_store)
        {
        	DB::enableQueryLog();
    
            $query = Self::where('favoritable_id', $id_store)
            				 ->where('user_id', $user_id)
                             ->first();
                             
            $queries = DB::getQueryLog();
    	    foreach($queries as $i=>$query)
    	    {
    	        Log::debug("Query $i: " . json_encode($query));
    	    }
    
            return $query;
        }
    }

I debug the query and the result is like this :

>array:3 [▼

>  "query" => "select * from `favorites` limit 1"

>  "bindings" => []

>  "time" => 1.28

>]

It looks, there are no conditions where

Why did it happen?

**Comment by taliptako** [comment]
You can use this https://github.com/rinvex/repository/tree/develop#findwhere

**Comment by sarfraznawaz2005** [comment]
Am I missing something cause package docs at the bottom say:

> Repositories intelligently pass missing called methods to the underlying model, so you actually can implement any kind of logic, or even complex queries by utilizing the repository model.

That seems to indicate that methods are looked up in chain to original eloquent methods so even if I don't use `findWhere` method of package, using `where` should also work ?

Also any idea of how to run custom queries using this package ?

**Comment by moschel26** [comment]
@taliptako, I still confused if use 2 condition. I try like this : 
    $query = Self->findWhere([
    							'favoritable_id', '=', $id_store, 
    							'user_id', '=', $user_id
    						]);

Seems it's not true

**Comment by taliptako** [comment]
@moschel26  `$query = Self::where('favoritable_id', $id_store)
        				 ->where('user_id', $user_id);
dd($query);`
Can you show the result of this ?

**Comment by moschel26** [comment]
Solved. Thanks

**Comment by moschel26** [comment]
@Omranic, Please, close this question. This already solve
