### ISSUE TITLE
How to solve error : Missing argument 1 for Rinvex\Repository\Repositories\EloquentRepository::delete() ?

### ISSUE THREAD

**Issue by moschel26** [rinvex/repository#134]
I have a table. The name is Favorites table. 

The table have some field. The field are id, user_id, favoritable_id, favoritable_type

I want delete record in the favorites table by user_id and favoritable_id

I try like this. This is My repository code 

    <?php
    
    namespace App\Repositories;
    
    use App\Models\Favorite;
    use Illuminate\Contracts\Container\Container;
    use Rinvex\Repository\Repositories\EloquentRepository;
    
    class FavoriteRepository extends EloquentRepository
    {
        
        // Instantiate repository object with required data
        public function __construct(Container $container)
        {
            $this->setContainer($container)
                 ->setModel(Favorite::class)
                 ->setRepositoryId('rinvex.repository.uniqueid');
        }
    
        public function deleteFavorite($user_id, $id_store)
        {
            $data = Self::where('favoritable_id', $id_store)
                        ->where('user_id', $user_id)
                        ->delete();
            return $data;
        } 
    }

When the code executed, there exist error like this : 

> ErrorException in EloquentRepository.php line 256: Missing argument 1
> for Rinvex\Repository\Repositories\EloquentRepository::delete(),
> called in
> C:\xampp\htdocs\mysystem\app\Repositories\FavoriteRepository.php
> on line 61 and defined

How to solve the error?

**Comment by taliptako** [comment]
You cant delete records like this for a now.You only can use ->delete($id) with primary id of the record.

**Comment by moschel26** [comment]
@taliptako, Great. Thanks

**Comment by Omranic** [comment]
Yes, it's just as @taliptako said.
You're trying to delete records the **Eloquent** way, which is not how repositories work.
You still can find these records through the repository like the following:
```php
$data = static::where('favoritable_id', $id_store)
                    ->where('user_id', $user_id)
                    ->findAll();
```

And then loop through these records and delete them one by one using Eloquent like though:
```php
foreach ($data as $item) {
    $item->delete();
}
```

I don't see any need to use repositories for deletion as it doesn't do anything special under the hood for this process.
