### ISSUE TITLE
Cache problem with PhpRedis

### ISSUE THREAD

**Issue by taliptako** [rinvex/repository#135]
I'm using Laravel 5.4 with rinvex develop branch.
My Code
`public function testRinvex(PostRepository $repository)
    {
        return $repository->findAll();
    }` 
It is working with predis but when i switch to phpredis which is new in laravel 5.4 i'm getting this error. I also test my phpredis functions get put etc they are working.But this problem still can be about laravel framework.
![screenshot from 2017-01-28 00-19-08](https://cloud.githubusercontent.com/assets/2073785/22388125/9ae19e30-e4e7-11e6-8f74-fa81f1dd7b66.png)

**Comment by rsdev000** [comment]
Hi
Take a look to this issue:

https://github.com/laravel/framework/pull/17627

Cheers

**Comment by taliptako** [comment]
This problem fixed with the laravel framework 5.4.7
