### ISSUE TITLE
Not working with Laravel 5.4?

### ISSUE THREAD

**Issue by cewlbird** [rinvex/repository#136]
Hi,

first of all thank you for this greate package! 

Will there be any Laravel 5.4 support?
Because I saw in the commits that you reverted the 5.4 support.

There are errors when trying to create an entity with your package.

`Type error: Argument 1 passed to Rinvex\Repository\Listeners\RepositoryEventListener::entityCreated() must implement interface Rinvex\Repository\Contracts\RepositoryContract, string given`

Regards,

CewlBird

**Comment by Omranic** [comment]
Yes, Laravel 5.4 support will be available very soon on the `dev-develop` branch and then will make it to the next major release later on, but the 2.x branch will kept compatible with up to L5.3.

**Comment by cewlbird** [comment]
Awesome. glad to hear that.
Again thank you for this great work, really looking forward for more awesome stuff!

**Comment by rsdev000** [comment]
@Omranic Hi. Do you have an ETA ?

**Comment by rsdev000** [comment]
Hi.

There's an issue with latest dev-develop branch. 

```php
$repo->setCacheDriver('foobar');
```
Doesn't throw any error as 2.0.2 do.

**Comment by Omranic** [comment]
This Midnight UTC 😬

**Comment by Omranic** [comment]
Fixed on **dev-develop** please composer update & post again if there's still any other issues. Sorry for the long wait 🙂  e2226399eb315f84f5ef3398c1ccdfec8540b56c

**Comment by rsdev000** [comment]
Thank you very much :)
