### ISSUE TITLE
¿Cuando estará disponible para laravel 5.4?

### ISSUE THREAD

**Issue by Daespinosag** [rinvex/repository#140]

**Comment by Omranic** [comment]
Laravel 5.4 is currently supported on the `dev-develop` branch, you can use the develop branch for now until it's tagged 🙂   Feel free to reopen if you've any issues 👍

**Comment by Daespinosag** [comment]
Otra pregunta : ¿ Se pueden usar joins extendiendo del EloquentRepository? ¿Como?

**Comment by noxify** [comment]
I hope google translate works as expected.

If you're asking about query joins, please check: https://github.com/rinvex/repository/issues/107

**Comment by Daespinosag** [comment]
Thanks,I will look at it , Sorry my English is bad enough.
