### ISSUE TITLE
How to solve Type error: Argument 1 passed to Rinvex\Repository\Repositories\EloquentRepository::findWhereNotIn() must be of the type array?

### ISSUE THREAD

**Issue by moschel26** [rinvex/repository#141]
My query is like this :

    $this->user_repository->findWhereNotIn('id', [1, 2, 3, 4]);

When executed, there exist error like this : 

>   [Symfony\Component\Debug\Exception\FatalThrowableError]   Type
> error: Argument 1 passed to
> Rinvex\Repository\Repositories\EloquentRepository::findWhereNotIn()
> must be of the type array, string given, called in
> C:\xampp\htdocs\myshop\app\Console\Commands\Check.php
> on line 48

Whereas in the tutorial https://github.com/rinvex/repository#findwherenotin, it looks like my query is correct

How can I solve it?

**Comment by noxify** [comment]
Hi,

based on the tutorial, your code is right, BUT based on the appended notes

> Notes:
> 
> Signature of all of the findWhere, findWhereIn, and findWhereNotIn methods has been changed since v2.0.0.
> All of the findWhere, findWhereIn, and findWhereNotIn methods utilize the where, whereIn, and whereNotIn methods respectively, and thus takes first argument as an array of same parameters required by the later ones.

The first parameter must be be an array.

You can find an example in the `tests` directory inside the `develop` branch.
https://github.com/rinvex/repository/blob/develop/tests/EloquentRepositoryTest.php#L78

Hope this solves your problem.

**Comment by moschel26** [comment]
@noxify, Great. It works. Thanks
