### ISSUE TITLE
Clear cache after model events

### ISSUE THREAD

**Issue by iwex** [rinvex/repository#147]
Why not to add possibility of cache clearing after creating/updating/deleting eloquent model?
Or, how can I write Unit tests with `factory()->create()`?

**Comment by Omranic** [comment]
Well, if I understood you well, then that's already implemented here `https://github.com/rinvex/repository/blob/develop/src/Listeners/RepositoryEventListener.php`

**Comment by iwex** [comment]
@Omranic no, it only listens for https://github.com/rinvex/repository/blob/develop/src/Repositories/EloquentRepository.php#L198 events. So, should I create new models only through `$repository->create()`?
Namely:
```php
$entities = factory(App\User::class, 3)->make();
$entities->each(function (User $user) use ($repo) {
    $repo->create($user->toArray());
});
```

**Comment by Omranic** [comment]
Well, that's something outside the scope of this package then.
Maybe you've to give the other package https://github.com/rinvex/cacheable a look which seems to be what you're looking for..
