### ISSUE TITLE
Why dev-develop required PHP 7 ?

### ISSUE THREAD

**Issue by erozqba** [rinvex/repository#148]
Laravel 5.4 gives support for PHP 5.6.4. and dev-develop gives support for Laravel 5.4, why does dev-develop not support PHP 5.6.4?

**Comment by rsdev000** [comment]
Hi. Because the dev-develop branch will turn in the next version of the package and it requires php 7. Php 5.6 is not actively supported since january 19th: http://php.net/supported-versions.php . 
Later this year, laravel 5.5 will drop php 5.6 support .

Cheers

**Comment by Omranic** [comment]
Just confirming that all stable coming releases of all of our packages will require at least **PHP v7.0+** and **Laravel v5.5** for Laravel packages.
