### ISSUE TITLE
 composer update: Class 'Rinvex\Repository\RepositoryServiceProvider' not found

### ISSUE THREAD

**Issue by rsdev000** [rinvex/repository#19]
Hi. good morning.
After a composer update i'm getting this error. Even on a fresh install.
Steps to reproduce:
1 - Create a new laravel project - laravel new projecttest
2 - Add rinvex/repository to composer.json - composer require rinvex/repository
3 - Add Rinvex\Repository\RepositoryServiceProvider::class to config/app.php
3 - composer update - throws the error

Any tip? It was working ok yesterday.

cheers

**Comment by Omranic** [comment]
Mornings @rsdev000 
You know what? I love feedback, I love fixing bugs 😄 
Bug confirmed: Wrong PSR-4 namespace for `RepositoryServiceProvider` class. It must be `namespace Rinvex\Repository\Providers;` .. Fix in progress 😉

**Comment by rsdev000** [comment]
lol. i was looking at that file and missed that. need a coffee
