### ISSUE TITLE
Filtering?

### ISSUE THREAD

**Issue by ionut-tanasa** [rinvex/repository#20]
Hi.

It would be cool to have some kind of more advanced filtering based on query strings or using simple classes for each filter type.

A simple example would be : 

example.com/users?search=field**:**operator**:**value ... and so on.

Since I'm planning to use your package intensively I would be cool to have this feature.

What do you think?

**Comment by Omranic** [comment]
Thank you @ionut-tanasa for you awesome suggestion 😊 
Actually that was partially implemented in the development phase, but decided to remove the whole filtration functionality before release as it's out of the scope of this package.

But here's the good news, a complete and intensive fully-featured `DataGrid` package is currently under development, which will utilize the repository package and adds almost every wild idea of data filtration using parameters programmatically, or through query strings 😉 It's difficult to announce ETA at this stage, so keep an eye of our productions 😄

**Comment by ionut-tanasa** [comment]
@Omranic cool. did not knew about the other package :)

Can't wait
