### ISSUE TITLE
Laravel readme example - Bind interface to implementation

### ISSUE THREAD

**Issue by ionut-tanasa** [rinvex/repository#21]
It would be nice to have an example on the readme to bind an interface to an implementation.

Give this interface: 

```php
interface UsersRepository extends \Rinvex\Repository\Contracts\RepositoryContract {}
```

And the following implementation : 

```php
class UsersEloquentRepository extends \Rinvex\Repository\Repositories\EloquentRepository implements UsersRepository {}
```

In a Laravel Service Provider we'd have `$this->app->bind(UsersRepository::class, UsersEloquentRepository::class)`

This way we don't have to `new` the repository implementation. Using dependency injection (i.e. injecting the UsersRepository in a controller) the IoC Container would take care of other dependencies that our app may depend on and new them up under the hood.

What do you think ?

**Comment by Omranic** [comment]
@ionut-tanasa Cool, let's do it 👍 `#approved`

**Comment by ionut-tanasa** [comment]
@Omranic another quick suggestion if I may.

I'd suggest to switch to a wiki instead of the readme file. IMHO it tends to get too long.

Consider giving a quick read to this [article](https://dotdev.co/how-to-write-a-readme-that-rocks-bc29f279611a#.a65c8kp6m)

**Comment by Omranic** [comment]
Yeah, I agree. I'll read that article & see what we can do.. 👍 
Thanks for your support, keep up the good work 😉

**Comment by Omranic** [comment]
Example added in 71afcdbcbbac1647a017190eddbf47ea4d1d25cb 👍
