### ISSUE TITLE
Reset "wheres"

### ISSUE THREAD

**Issue by rsdev000** [rinvex/repository#30]
Steps to reproduce
 
- Perform two or more repository queries in the same request

```php
$x = $this->repository->setCacheLifetime(0)->findWhere(['post_id' => 10]);
$y = $this->repository->setCacheLifetime(0)->findWhere(['post_id' => 20]);
```

Expected executed queries
```sql
select * from `post` where `post_id` = '10'
select * from `post` where `post_id` = '20'
```

Executed queries
```sql
select * from `post` where `post_id` = '10'
select * from `post` where `post_id` = '10' and `post_id` = '20'
```

Didn't test other find* methods

Cheers

**Comment by Omranic** [comment]
Confirmed! This has to be rethought & things to be fixed. Working on it..

**Comment by rsdev000** [comment]
Tough ones :) ?

**Comment by Omranic** [comment]
Well, major re-write for better, and more clean code. All

**Comment by Omranic** [comment]
Sorry, deleted your recent reply by mistake! On mobile!!
Well, major re-write in progress for more clean and consistent code, with focus on flexible filtration for any queries, better compatibility and caching. Hopefully I'll complete it by tonight. :smile:

**Comment by Omranic** [comment]
Almost done, clean code, more intuitive, add where clauses to any query and still cash results granuly, simplify initialization, reset repository object after query execution, and lastly I may be able to add tests cases in this update 🙂
