### ISSUE TITLE
Reset model  

### ISSUE THREAD

**Issue by rsdev000** [rinvex/repository#45]
I'm getting duplicate queries as the first issue before this refactor:

$x = $this->repository->setCacheLifetime(0)->findWhere(['post_id', '=', 10, 'or']);
$y = $this->repository->setCacheLifetime(0)->findWhere(['post_id', '=', 20, 'and']);

Queries executed

select * from `post` where `post_id` = '10'

select * from `post` where `post_id` = '10' and `post_id` = '20'

Updated local develop branch a few minutes ago.

Maybe you could check the number of elements in the where array before list(...) and set $boolean with a default. Otherwise there's an error if the fourth element is empty

**Comment by Omranic** [comment]
Perfect catching 👍 
Confirmed, fixed

**Comment by rsdev000** [comment]
Yes it is :)

**Comment by rsdev000** [comment]
Updated the first comment about the fourth element of the where array

**Comment by Omranic** [comment]
`$boolean` already have a default value of 'and'. Am I missing something?

**Comment by rsdev000** [comment]
$x = $this->repository->setCacheLifetime(0)->findWhere(['post_id', '=', 10]); throws an error:

ErrorException in EloquentRepository.php line 138:
Undefined offset: 3

**Comment by Omranic** [comment]
Gotcha 👍

**Comment by rsdev000** [comment]
Spent the last 4 years working as quality assurance engineer in one of the backend apps of https://www.jumia.com.eg/ :)

**Comment by Omranic** [comment]
Oh, wow. Sounds cool.

**Comment by rsdev000** [comment]
100% made in oporto,portugal. not working there anymore
