### ISSUE TITLE
Container Usage

### ISSUE THREAD

**Issue by taylorotwell** [rinvex/repository#48]
I'm not you really need to inject the container into the Eloquent repository. You can just "new" up Eloquent models manually. Typically they wouldn't / shouldn't have constructor dependencies. Unless you have a strong reason for needing the container?

**Comment by Omranic** [comment]
Well, I agree that injecting container makes it a bit more complicated than required, but that's to make it more agnostic to **Eloquent**. I'm sure it could be done much more simpler than current implementation if it's tightly coupled to Eloquent. I'm using `config`, `cache`, and `events` services from the IoC, that's current use of the container. 

I wish I could simplify the code, and minimize requirements. What do you think @taylorotwell, any thoughts?

**Comment by taylorotwell** [comment]
I'm sure it's probably fine :)
