### ISSUE TITLE
`findWhere` can only query on one column

### ISSUE THREAD

**Issue by ninjaparade** [rinvex/repository#49]
the `v1.0.*` version allowed passing an array of more than 1 column to query against, where as now we can only pass one column and an operator.

Is it possible to allow being able to query more than 1?

example

```$repository->findWhere(['id' => 1, 'active' => true]);```

**Comment by Omranic** [comment]
Well, in **v2.0.*** it's more consistent and possible through chaining `where` methods before executing the query. Actually I was thinking in omitting `findWhere*` methods to prevent such confusion. Example:
```php
$repository->where('id', '=', 1)->where('active', '=', true)->findAll();
```
It's much like query builder normal syntax now.. Hope this helps 😉

**Comment by ninjaparade** [comment]
Ya this does work I just wish I could do one `findWhere()` and pass all the conditions in one spot.

Either way `v2.0.*` is pretty awesome. 👍

**Comment by Omranic** [comment]
While the API is much more consistent & stable, I still feel there's a room for enhancement. 
That's why feedback is always welcome & so important ;)
