### ISSUE TITLE
Database Transactions

### ISSUE THREAD

**Issue by ionut-tanasa** [rinvex/repository#50]
Cool feature to have would be transactions. 

Enabled globally or per repository, maybe?
 
Maybe for the EloquentRepository.

What do you think?

**Comment by Omranic** [comment]
I like this idea 😃 And yes, probably it would be only for `EloquentRepository`
Let's see what we can do for it after releasing next package 😉

**Comment by rsdev000** [comment]
This one is a "nice to have" :)

**Comment by Omranic** [comment]
Anyone up to PR? It would be nice 😄
