### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by ionut-tanasa** [rinvex/repository#52]
Would you be kind enough to move the docs to the wiki? I think the readme file is getting too long. Since you are doing a great job with this package, I wouldn't want the docs to suck 😄 

I know I asked you some time ago, but it would be cool to do it like this:

https://github.com/ionut-tanasa/repository/wiki

Much cleaner, imho.

If you want you can give me access and I can manage it. Or merge my wiki. I just took the readme and splitted it in sections.

**Comment by Omranic** [comment]
Thought about it, and read some articles about the topic but didn't take that decision yet. Maybe cuz myself like the one-page documentation where I can search for anything & everything. But still you've a good point.

So, what should go into the main repository readme in your opinion?

**Comment by ionut-tanasa** [comment]
# Rinvex Repository

![Rinvex Repository Diagram](https://rinvex.com/assets/frontend/layout/img/products/rinvex.repository.diagram.png)

**Rinvex Repository** is a simple, intuitive, and smart implementation of Active Repository with extremely flexible & granular caching system for Laravel, used to abstract the data layer, making applications more flexible to maintain.

[![Packagist](https://img.shields.io/packagist/v/rinvex/repository.svg?label=Packagist&style=flat-square)](https://packagist.org/packages/rinvex/repository)
[![License](https://img.shields.io/packagist/l/rinvex/repository.svg?label=License&style=flat-square)](https://github.com/rinvex/repository/blob/develop/LICENSE)
[![VersionEye Dependencies](https://img.shields.io/versioneye/d/php/rinvex:repository.svg?label=Dependencies&style=flat-square)](https://www.versioneye.com/php/rinvex:repository/)
[![Scrutinizer Code Quality](https://img.shields.io/scrutinizer/g/rinvex/repository.svg?label=Scrutinizer&style=flat-square)](https://scrutinizer-ci.com/g/rinvex/repository/)
[![Code Climate](https://img.shields.io/codeclimate/github/rinvex/repository.svg?label=CodeClimate&style=flat-square)](https://codeclimate.com/github/rinvex/repository)
[![StyleCI](https://styleci.io/repos/61269204/shield)](https://styleci.io/repos/61269204)
[![SensioLabs Insight](https://img.shields.io/sensiolabs/i/8394bf3e-26c8-415a-8952-078b41110181.svg?label=SensioLabs&style=flat-square)](https://insight.sensiolabs.com/projects/8394bf3e-26c8-415a-8952-078b41110181)

## Features

- Cache, Cache, Cache!
- Prevent code duplication.
- Reduce potential programming errors.
- Granularly cache queries with flexible control.
- Apply centrally managed, consistent access rules and logic.
- Implement and centralize a caching strategy for the domain model.
- Improve the code’s maintainability and readability by separating client objects from domain models.
- Maximize the amount of code that can be tested with automation and to isolate both the client object and the domain model to support unit testing.
- Associate a behavior with the related data. For example, calculate fields or enforce complex relationships or business rules between the data elements within an entity.

Click here for the docs.

This should do it.

**Comment by Omranic** [comment]
Replicated docs to wikis nicely https://github.com/rinvex/repository/wiki

But will keep README as it is for now, think of it as offline docs for those who got the package and playing with it offline, they deserve complete documentation as well, don't you think? 🙂
