### ISSUE TITLE
Pagination methods returns same results for any page

### ISSUE THREAD

**Issue by tzurbaev** [rinvex/repository#53]
As of v2.0.0 `paginate()` and `simplePaginate()` methods are returning the same results if you're not providing `$page` argument explicitly (but there's no info about it in documentation).

This happens because both `paginate` and `simplePaginate` methods provides their arguments to `BaseRepository::executeCallback` via `func_get_args` but [its documentation](http://php.net/manual/en/function.func-get-args.php) says:

> Note: This function returns a copy of the passed arguments only, and does not account for default (non-passed) arguments.

So, all non-passed arguments are ignored and only `$perPage` (which is obviously the same for every request) is provided.

As a quick-fix I did this:
```php
use Illuminate\Pagination\Paginator;

[...]

$args = [$perPage, $attributes, $pageName, $page ?: Paginator::resolveCurrentPage($pageName)];
```

and I'm sending this array to `executeCallback` instead of `func_get_args`.

Another fix without touching vendor code is to provide all arguments from client code:
```php
$paginator = $repository->paginate(25, ['*'], 'page', intval($request->input('page', 1)));
```

If first fix is ok for you, I'll create PR, just let me know.

**Comment by Omranic** [comment]
Thank you for your issue reporting, I'm in a business trip for few days, so I'll check it once I'm back 👍

**Comment by Omranic** [comment]
Hello @tzurbaev, sorry for the delay 😁

I've read your issue & it seems there's misunderstanding for how the `executeCallback` method works, you don't have to worry about the `func_get_args` method as it's not used in any logic other than the MD5 hashing for cache keys, so to make it clear all passed arguments are passed explicitly to the underlying model methods, here:
```php
    public function paginate($perPage = null, $attributes = ['*'], $pageName = 'page', $page = null)
    {
        return $this->executeCallback(get_called_class(), __FUNCTION__, func_get_args(), function () use ($perPage, $attributes, $pageName, $page) {
            return $this->prepareQuery($this->createModel())->paginate($perPage, $attributes, $pageName, $page);
        });
    }
```
As you can see, all passed arguments `$perPage`, `$attributes`, `$pageName`, `$page` are explicitly passed to the model, so there should be no problem, and actually it's working fine as expected, example:
```php
$repository->paginate(5, ['*'], 'page', 2)->toArray();
```
Now, we're querying the first 5 records, in the second page.

Documentation will be updated to reflect this pagination example, please if you've any other issues or if there's anything I didn't get correctly feel free to update this issue again 👍

**Comment by tzurbaev** [comment]
Hey, @Omranic, thank you for your response.

> you don't have to worry about the func_get_args method as it's not used in any logic other than the MD5 hashing for cache keys

But as I wrote, `func_get_args` ignores default (non-passed) argument values. And result of `func_get_args` is used to generate cache key. When `$page` value is not provided, repository will generate the same cache key for any requests (no matter what `?page=N` value is) and return the same data for any page.

```php
$repository->paginate(5, ['*'], 'page', 2)->toArray();
```
This call returns correct data, but I think these methods (repository's `paginate`/`simplePaginate`) should be compatible with Eloquent ones. Do we really need to pass all 4 arguments?

**Comment by Omranic** [comment]
@tzurbaev Yes, I agree. And I think #54 fixed this issue already as it's now passed explicitly. Right?

**Comment by tzurbaev** [comment]
@Omranic no, I've just added missing `$page` argument in #54. I'll do another PR today.
