### ISSUE TITLE
Extract Cache methods to a Contract / Implementation or Trait

### ISSUE THREAD

**Issue by ionut-tanasa** [rinvex/repository#57]
I saw that BaseRepository has all the methods for cache managing. Would be cleaner to have the logic in another class. 

SRP 😃 

What do you think?

**Comment by Omranic** [comment]
Any possible example for expected implementation?

**Comment by Omranic** [comment]
Done, it would be nice if you can feedback before merging to `master` branch 🙂

**Comment by rsdev000** [comment]
Hi. So far, so good :) . Didn't get any errors.

**Comment by ionut-tanasa** [comment]
Awesome!

The part of overriding stuff that I wrote in the initial description was just a late brain fart of mine 😄 
Couldn't come up with no example 😞
