### ISSUE TITLE
Return object instead of array for CrUD operations

### ISSUE THREAD

**Issue by ionut-tanasa** [rinvex/repository#59]
Hey, me again ...

Wouldn't it be better to have something like this in the `create`, `update` and `delete` methods:

```php
// Find the given instance
$instance = $id instanceof Model ? $id : $this->find($id);

if ($instance) {
    // Fill instance with data
    $instance->fill($attributes);

    // Update the instance
    $updated = $instance->save();

    // Fire the updated event
    $this->getContainer('events')->fire($this->getRepositoryId().'.entity.updated', [$this, $instance]);

}

return $updated ? $instance : $updated;
```

So why?

Lets take this controller method as an example:

```php
/**
 * GuestsController::update
 *
 * Update the specified Guest in storage.
 *
 * @param GuestUpdateRequest $request
 * @param  int               $id
 *
 * @return \Illuminate\Http\Response
 */
public function update(GuestUpdateRequest $request, $id)
{
    $entity = $this->guestsRepository->update($id, $request->all());
    if (is_array($entity) && $entity[0]) {
        return $this->response->item($entity[1], new GuestTransformer);
    }

    return $this->response->errorInternal();
}
```

I have to use indexes if from the repository I'm receiving an array ... Using my suggestion I would do like this and it would be a lot more cleaner:

```php
/**
 * GuestsController::update
 *
 * Update the specified Guest in storage.
 *
 * @param GuestUpdateRequest $request
 * @param  int               $id
 *
 * @return \Illuminate\Http\Response
 */
public function update(GuestUpdateRequest $request, $id)
{
    $entity = $this->guestsRepository->update($id, $request->all());
    if ($entity) {
        return $this->response->item($entity, new GuestTransformer);
    }

    return $this->response->errorInternal();
}
```

Another use case would be when I would like to do something else with my entity. Access some other properties or pass the whole object to something else.

What do you think?
Did you chose to return an array from the methods for a particular reason?

**Comment by Omranic** [comment]
While your example seems to be more intuitive, the main reason for returning an array is to get feedback what happened for the operation, succeeded or failed in addition to the object itself, do you think there's better way to do so while returning

**Comment by Omranic** [comment]
Through your example I see you don't care the status if it's success, which is acceptable solution.. I'll consider this tweak.. 👍

**Comment by ionut-tanasa** [comment]
Well you actually don't need to return the result from `save` method or any other method. A proper exception would be thrown by Laravel I guess. 

The find method would throw a ModelNotFoundException. 

The save method would throw some database related exception if something goes wrong. 

And so on...

At the bottom of the method you could leave updated ? Instance : null. And instead of null return false. Both will do I guess.

**Comment by kevindierkx** [comment]
@ionut-tanasa the `findOrFail` method throws an exception `find` just returns null. Same goes for the save method. Create, update and delete return `false` if I'm not mistaking.

But more on topic it does make sense to me to return the instance directly and just return false or null for find methods when something goes wrong or didn't happen. (illuminate/database does the same thing anyway)
