### ISSUE TITLE
About Criterias

### ISSUE THREAD

**Issue by evsign** [rinvex/repository#60]
Hi.
Just simple use case:
We want to rename a column in big application. Without criterias we also need to rename all usings of old column name in code. With criterias - we need to rename only in one place. Profit)
Also criterias give possibility to maintain database in most uniform view and reuse repeating parts of sql queries.

**Comment by Omranic** [comment]
Hello @evsign, could you please give an real code example for your use case as I never see any situation that couldn't be achieved with `where` conditions currently supported. That would be much helpful to understand the importance of this feature and maybe implement it.. 😃

**Comment by evsign** [comment]
I see no need for any code example) I provide a real use case for this feature. Its just a way to encapsulate and reuse sql.
"Where" is taking column names in there arguments, which help to build sql queries. Criterias provide complete part of query, which can be used in any part of application without fear to broke something when column will be renamed. Because we can just rename usage of this column in one place and all queries will be working as well, instead of renaming all usages of where clause with this column name in code.

As second part of profit is a way to build queries with using business oriented representations (meaningfull class names which characterize some action).

As third is a way to maintain database in uniform view/style/convention. I mean, criterias can provide a way to checking a db architecture for this. Every time if you catch yourself behind creating new criteria which do the same as existed one - this mean something is wrong)

Another use case:
I think you see already something like this https://dotdev.co/writing-advanced-eloquent-search-query-filters-de8b6c2598db#.2oomop1p3
This can be implemented through criterias.

Everything is limited only by our imagination :smiley:

**Comment by ionut-tanasa** [comment]
+1 on this one. Criterias can extract complex queries. 
You could pass the whole query builder to it and the go from there. 

Another plus will be filtering based on query string data. I would create a class that translates the query string params in appropriate Criteria classes.

**Comment by ionut-tanasa** [comment]
@Omranic @evsign how do you guys think we could implement this?

**Comment by evsign** [comment]
@ionut-tanasa Maybe on this or next weekend. Now i have much of work)

**Comment by Omranic** [comment]
A PR would be much appreciated. For those who already used criteria pattern extensively before, is there an optimal implementation currently available in other open source packages that could be influencing for us? For me I could say that `andersao/l5-repository` implementation is good enough for a starting point, don't you agree?

**Comment by evsign** [comment]
@Omranic i just already use their repository implementation in one project and faced with some not usable things about their criterias implementation and i think i can pay attention for this) For example, possibility to use closure as criteria)

**Comment by evsign** [comment]
@Omranic and in some cases we need possibility for nested criterias, which missing in `andersao/l5-repository`)

**Comment by Omranic** [comment]
@evaign Up to PR?

**Comment by Omranic** [comment]
Finally merged #76 , thanks @evsign really appreciated 😄

**Comment by evsign** [comment]
@Omranic you're welcome) hope this will be useful feature)
