### ISSUE TITLE
paginate() and simplePaginate() always return the first cached results even when a page is provided in the url

### ISSUE THREAD

**Issue by kevindierkx** [rinvex/repository#61]
As discussed in #53 the paginate and simplePaginate always return the first cached result for every page when the `paginate()` or `simplePaginate()` arguments are left empty.

This is expected since the default for the `$page` argument is null and is cached as null.

This becomes a hassle when you want the unique results for different pages, the `$page` argument is the last argument you can specify forcing you to specify perPage, attributes and the pageName every time you want paginated results.

`illuminate/database` resolves this by checking the `page` parameter on the request and returning the first page by default when no page parameter is provided.

Looking at the `EloquentRepository` all request are piped through the `executeCallback` method. This method handles all the fancy caching logic and returns either the results of the  provided callback or the already cached results.

This is where it goes wrong, `executeCallback` always uses the function arguments to determine the correct cache. This works for indexes and shows but breaks for paginated results.
This happens because the cached results are returned before the Eloquent model could check if it's handling the same page as before.

To resolve this we need to add some extra logic to the `paginate` and `simplePaginate` methods. They should append the requested page parameter from the url to the function arguments when it is not the default value as specified on the method.

This can be done using the `illuminate/paginator` this is already a requirement when you want paginated results.

**I've already got a pull request made, this issue is just for justification**

**Comment by Omranic** [comment]
Thanks @kevindierkx, perfectly explained 👍
