### ISSUE TITLE
Swap database connection on the fly

### ISSUE THREAD

**Issue by ionut-tanasa** [rinvex/repository#71]
We could add a getter and a setter for a property on the BaseRepository and call `setConnection` on the model underneath.

A quick example could be `$repository->setConnection('sqlsrv')->...`.

I'd add a default fallback configuration key to `rinvex.repository.php`

**Comment by Omranic** [comment]
Implemented & merged into `develop`, @ionut-tanasa you can test it & tell me if there's any notes 👍

**Comment by ionut-tanasa** [comment]
@Omranic awesome! Will test soon. I have just the right example at work :)
