### ISSUE TITLE
[Proposal] Add support for lazy eager loading

### ISSUE THREAD

**Issue by gaillafr** [rinvex/repository#84]
Hi,

As describe here: https://laravel.com/docs/master/eloquent-relationships#lazy-eager-loading, it would be nice to be able to do something like:
```php
$repository->findAll()->load(['comments', 'comments.user']);
```

Thanks,
Kind regards.

**Comment by ionut-tanasa** [comment]
Well I don't know how we could implement this since `findAll` returns cached results. Embedding data after could be tricky. 

@Omranic thoughts on this one?

**Comment by Omranic** [comment]
Sorry, didn't catch this issue. Anyway I guess I agree with @ionut-tanasa 
@gaillafr Unless you've other thoughts it's really tricking to deal with this sort of things. Remember that you still have the ability to use the `with` method to retrieve relations on demand, but that will be considered a different query & cached separately.
