### ISSUE TITLE
Add before/after hooks

### ISSUE THREAD

**Issue by ionut-tanasa** [rinvex/repository#98]
`beforeCreate` / `afterCreate`
`beforeUpdate` / `afterUpdate`
`beforeDelete` / `afterDelete`

**Comment by Omranic** [comment]
There's already '.entity.creating' & '.entity.created' events, isn't that what you mean?

**Comment by ionut-tanasa** [comment]
Given `UserRepository`, I can define those 6 methods if I want to do some logic, passing the model or the query builder or both maybe, before and after a certain action.

Quick snippet: 

```php
public function update($id, array $attributes = [])
{
    $updated = false;
    // Find the given instance
    $instance = $id instanceof Model ? $id : $this->find($id);
    if ($instance) {
        // Fire the updated event
        $this->getContainer('events')->fire($this->getRepositoryId().'.entity.updating', [$this, $instance]);
        // Fill instance with data
        $instance->fill($attributes);

       // if method exists call beforeUpdate passing $instance

        // Update the instance
        $updated = $instance->save();

        // if method exists call afterUpdate passing $instance

        // Fire the updated event
        $this->getContainer('events')->fire($this->getRepositoryId().'.entity.updated', [$this, $instance]);
    }
    return $updated ? $instance : $updated;
}
```

Something like this

Catching the event in some other part of the application it's not right, imo. This way the logic stays within the repository class.

**Comment by evsign** [comment]
I think there is enough of laravel model events https://laravel.com/docs/5.3/eloquent#events

**Comment by Omranic** [comment]
@ionut-tanasa Well, that's still exactly the same as:
```php
$this->getContainer('events')->listen($this->getRepositoryId().'.entity.updating', [$this, $instance]);
```
Which is already supported, and while you could listen to it from inside the repository itself, you can still do so globally. Just plain Laravel events handling..

**Comment by Omranic** [comment]
Same as:
```php
Event::listen('event.name', function ($foo, $bar) {
    //
});
```

**Comment by ionut-tanasa** [comment]
Sooo better to stick with events, you say ? 😄

**Comment by ricardovigatti** [comment]
Yes, both listeners are called.

**Comment by ionut-tanasa** [comment]
Events it is then. :)
